### ISSUE TITLE
Can I publish it to Chinese video website

### ISSUE THREAD

**Issue by valetzx** [Rapiz1/DungeonRush#31]
can i change the drawable and repack reupload. and i will mark your github link down，and i want translate some text to Chinese after

**Comment by yujqiao** [comment]
Feel free to do so. But i also recommand you to replace the music if you decide to spread it widely. Because I don't know if there are copyright issues.



---Original---
From: ***@***.***&gt;
Date: Sun, Mar 14, 2021 08:17 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Rapiz1/DungeonRush] Can I publish it to Chinese video website (#31)




 
can i change the drawable and repack reupload. and i will mark your github link down，and i want translate some text to Chinese after

**Comment by valetzx** [comment]
> Feel free to do so. But i also recommand you to replace the music if you decide to spread it widely. Because I don't know if there are copyright issues.
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sun, Mar 14, 2021 08:17 AM To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [Rapiz1/DungeonRush] Can I publish it to Chinese video website (#31) can i change the drawable and repack reupload. and i will mark your github link down，and i want translate some text to Chinese after — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

ok thanks alot
